name: my_lol_profile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #dio for http request
  http: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #dotenv for .env docs
  flutter_dotenv: ^5.1.0
  flutter_lints: ^2.0.0
  
assets:
   .env
flutter:
  uses-material-design: true
